services:
  backend:
    build:
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./:/app 
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=db
      - PORT=8080
      - FRONT_URL=${FRONT_URL}
    depends_on:
      - db

  db:
    image: "postgres:15-alpine"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB={POSTGRES_DB}
    volumes:
      - db-store:/var/lib/postgresql/data

volumes:
  db-store:
